server:
  port: 8888
  shutdown: graceful
  servlet:
    context-path: /cloudConfigServer

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaahilArora/cloudConfigServer.git
          timeout: 10 # in seconds
          refresh-rate: 30 # in seconds
          default-label: master # default git branch
          repos:
            cloudConfigServer-test:
              pattern: "*cloudConfig-test*"
              uri: https://github.com/SaahilArora/cloudConfigServer.git
              searchPaths: test, test/*
