server:
  port: 8888
  shutdown: graceful
  servlet:
    context-path: /cloudproperty

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/arorasaahil1994/cloudproperty.git
          timeout: 10 # in seconds
          refresh-rate: 30 # in seconds
          default-label: main # default git branch
          repos:
            cloudproperty-test:
              pattern: "*cloudproperty-test*"
              uri: https://gitlab.com/arorasaahil1994/cloudproperty.git
              searchPaths: test, test/*
